[options]
admin_passwd = $pbkdf2-sha512$600000$yhnjXGttrfV.b62VMgZgDA$CRZGNsgutip2r9gSzn5IGeDrrQ7dG8oYQvtcM4k.0NuoaAsnOPycoU/bi4sN0c0yeyiRgHCbiBUIym3MidIb/Q
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = 123456
dbfilter = .*
addons_path = C:\Users\shish\OneDrive\Documents\odoo\community\addons,C:\Users\shish\OneDrive\Documents\odoo\custom-addons\addons
default_productivity_apps = True

